src/AppBundle/Entity/Product.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Product
 *
 * @ORM\Table(name="product")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ProductRepository")
 */
class Product
{
    const SERVER_PATH_TO_IMAGE_FOLDER = 'images/product';
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Brand
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Brand", inversedBy="products")
     * @ORM\JoinColumn(name="brand_id", referencedColumnName="id")
     */
    private $brand;

    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Category", inversedBy="products")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $category;

    /**
     * @var PropertyValue[]
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\PropertyValue", inversedBy="products")
     * @ORM\JoinTable(name="product_to_property_values")
     */
    private $propertyValues;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="code", type="string", length=255)
     */
    private $code;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var int
     *
     * @ORM\Column(name="count", type="integer")
     */
    private $count;

    /**
     * @var float
     *
     * @ORM\Column(name="price", type="float")
     */
    private $price;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=255)
     */
    private $image;

    /**
     * @var UploadedFile
     */
    private $file;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return Brand
     */
    public function getBrand()
    {
        return $this->brand;
    }

    /**
     * @param Brand $brand
     */
    public function setBrand($brand)
    {
        $this->brand = $brand;
    }

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param Category $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }

    /**
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * @param int $count
     */
    public function setCount($count)
    {
        $this->count = $count;
    }

    /**
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * @param float $price
     */
    public function setPrice($price)
    {
        $this->price = $price;
    }

    /**
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param string $image
     */
    public function setImage($image)
    {
        $this->image = $image;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Product
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set code
     *
     * @param string $code
     *
     * @return Product
     */
    public function setCode($code)
    {
        $this->code = $code;

        return $this;
    }

    /**
     * Get code
     *
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Product
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @return PropertyValue[]
     */
    public function getPropertyValues()
    {
        return $this->propertyValues;
    }

    /**
     * @param PropertyValue[] $propertyValues
     */
    public function setPropertyValues($propertyValues)
    {
        $this->propertyValues = $propertyValues;
    }

    /**
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param UploadedFile $file
     */
    public function setFile($file)
    {
        $this->file = $file;
    }

    public function getFullPathImage()
    {
        return self::SERVER_PATH_TO_IMAGE_FOLDER.'/'.$this->image;
    }

    /**
     * Manages the copying of the file to the relevant place on the server
     *
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function upload()
    {
        // the file property can be empty if the field is not required
        if (null === $this->getFile()) {
            return;
        }

        // we use the original file name here but you should
        // sanitize it at least to avoid any security issues

        // move takes the target directory and target filename as params
        $this->deleteOldImage($this->getImage());

        $newNameFile = md5($this->getFile()->getPathname()) .
            '_' . time() .
            '.' .$this->getFile()->getClientOriginalExtension();

        $this->getFile()->move(
            self::SERVER_PATH_TO_IMAGE_FOLDER,
            $newNameFile
        );

        // set the path property to the filename where you've saved the file
        $this->image = $newNameFile;

        // clean up the file property as you won't need it anymore
        $this->setFile(null);
    }

    /**
     * @param $name
     */
    private function deleteOldImage($name)
    {
        $fullPath = self::SERVER_PATH_TO_IMAGE_FOLDER.'/'.$name;

        if (!empty($name) && file_exists($fullPath)) {
            @unlink($fullPath);
        }
    }
}

src/AppBundle/Resources/views/about.html.twig
{% extends '@App/main.html.twig' %}

{% block main %}
    <h3>About Shop</h3>
    {{ about }}
{% endblock %}

src/AppBundle/Resources/views/contact.html.twig
{% extends '@App/main.html.twig' %}

{% block main %}
    <h3>Contact Info</h3>
    {{ contact }}
{% endblock %}

src/AppBundle/Resources/views/homepage.html.twig
{% extends '@App/main.html.twig' %}

{% block main %}
    <h3>Home page</h3>
{% endblock %}

src/AppBundle/Resources/views/main.html.twig
{% extends '::base.html.twig' %}

{% block content %}
        <nav class="navbar navbar-default navbar-static-top">
            {{ include('@App/menu.html.twig') }}
        </nav>
        <div class="container">
            <div class="col-md-2">
                {{ include('@App/filters.html.twig') }}
            </div>
            <div class="col-md-10">
                {% block main %}{% endblock %}
            </div>
        </div>
{% endblock %}

{% block stylesheets %}
    <style>
        body { background: #F5F5F5; font: 18px/1.5 sans-serif; }
    </style>
{% endblock %}

src/AppBundle/Resources/views/menu.html.twig
<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Shop</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ path('homepage') }}">Shop</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li class="{% if app.request.get('_route') == 'homepage' %}active{% endif %}">
                <a href="{{ path('homepage') }}">Home</a>
            </li>
            <li class="{% if app.request.get('_route') == 'products' %}active{% endif %}">
                <a href="{{ path('products') }}">Products</a>
            </li>
            <li class="{% if app.request.get('_route') == 'about' %}active{% endif %}">
                <a href="{{ path('about') }}">About</a>
            </li>
            <li class="{% if app.request.get('_route') == 'contact' %}active{% endif %}">
                <a href="{{ path('contact') }}">Contact</a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="{% if app.request.get('_route') == 'order' %}active{% endif %}">
                {% set basket = app.session.get('basket') %}
                <a href="{{ path('order') }}">Your basket: <span id="count-product">{{ basket|length }}</span></a>
            </li>
        </ul>
    </div><!--/.nav-collapse -->
</div>

src/AppBundle/Resources/views/order.html.twig
{% extends '@App/main.html.twig' %}

{% block main %}

    {% for product in products %}
        <div class="col-md-7 product" style="background-color: #eeeeee; padding: 15px; margin: 10px">
            <img height="50" src="{{ product.fullPathImage }}">
            <span>{{ product.name }}</span>
            <div>{{ product.price|e }}</div>
            <button class="btn btn-outline remove" data-action="{{ path('remove_product', {'id': product.id}) }}">Remove!</button>
        </div>
    {% endfor %}

    <div  class="col-md-7" style="background-color: #ca77a9;  padding: 15px; margin: 10px">
        <input class="info" name="sum" id="sum" value="{{ sum|e }}" readonly/>
    </div>

    <div  class="col-md-7">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/basket.js') }}"></script>
{% endblock %}

src/AppBundle/Resources/views/products.html.twig
{% extends '@App/main.html.twig' %}

{% block main %}

    {% for product in products %}
        <div class="col-md-7" style="background-color: #eeeeee; padding: 15px; margin: 10px">
            <img height="50" src="{{ product.fullPathImage }}">
            <span>{{ product.description }}</span>
            <div>{{ product.price|e }}</div>
            <button class="btn btn-primary buy" data-action="{{ path('add_product', {'id': product.id}) }}">Buy!</button>
        </div>
        
    {% endfor %}

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/basket.js') }}"></script>
{% endblock %}